import './js/artists.js';
import './js/feedbacks.js';
import './js/header.js';
import './js/hero.js';
import './js/modal.js';
import './js/api.js';
import './js/render-functions.js';
import './js/loader.js';
import './js/feedback-modal.js';